#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_EVA_")]
	public partial class ConexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConexionDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.DB_EVA_ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarConsumoDinero")]
		public int SP_InsertarConsumoDinero([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_REFERENCIA", DbType="NVarChar(100)")] string nOMBRE_REFERENCIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTO", DbType="Decimal(18,2)")] System.Nullable<decimal> mONTO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, nOMBRE_REFERENCIA, mONTO);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ObtenerViajesGuardados")]
		public ISingleResult<SP_ObtenerViajesGuardadosResult> SP_ObtenerViajesGuardados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_ObtenerViajesGuardadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ObtenerVehiculo")]
		public ISingleResult<SP_ObtenerVehiculoResult> SP_ObtenerVehiculo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_ObtenerVehiculoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ObtenerUsuarioPorGuid")]
		public ISingleResult<SP_ObtenerUsuarioPorGuidResult> SP_ObtenerUsuarioPorGuid([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_ObtenerUsuarioPorGuidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ObtenerUsuarioPorCorreo")]
		public ISingleResult<SP_ObtenerUsuarioPorCorreoResult> SP_ObtenerUsuarioPorCorreo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(50)")] string cORREO_ELECTRONICO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO);
			return ((ISingleResult<SP_ObtenerUsuarioPorCorreoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ObtenerHistorialConsumo")]
		public ISingleResult<SP_ObtenerHistorialConsumoResult> SP_ObtenerHistorialConsumo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_ObtenerHistorialConsumoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ObtenerHistorial")]
		public ISingleResult<SP_ObtenerHistorialResult> SP_ObtenerHistorial([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_ObtenerHistorialResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LoginUsuario")]
		public ISingleResult<SP_LoginUsuarioResult> SP_LoginUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(50)")] string cORREO_ELECTRONICO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO);
			return ((ISingleResult<SP_LoginUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarVehiculo")]
		public ISingleResult<SP_InsertarVehiculoResult> SP_InsertarVehiculo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MARCA", DbType="NVarChar(50)")] string mARCA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MODELO", DbType="NVarChar(50)")] string mODELO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ANO", DbType="Int")] System.Nullable<int> aNO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, mARCA, mODELO, aNO);
			return ((ISingleResult<SP_InsertarVehiculoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarViajeGuardado")]
		public ISingleResult<SP_InsertarViajeGuardadoResult> SP_InsertarViajeGuardado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_VIAJE", DbType="NVarChar(100)")] string nOMBRE_VIAJE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LATITUD_DESTINO", DbType="Decimal(10,6)")] System.Nullable<decimal> lATITUD_DESTINO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LONGITUD_DESTINO", DbType="Decimal(10,6)")] System.Nullable<decimal> lONGITUD_DESTINO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, nOMBRE_VIAJE, lATITUD_DESTINO, lONGITUD_DESTINO);
			return ((ISingleResult<SP_InsertarViajeGuardadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarViajeGuardado")]
		public ISingleResult<SP_EliminarViajeGuardadoResult> SP_EliminarViajeGuardado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_VIAJE", DbType="NVarChar(100)")] string nOMBRE_VIAJE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LATITUD_DESTINO", DbType="Decimal(10,6)")] System.Nullable<decimal> lATITUD_DESTINO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LONGITUD_DESTINO", DbType="Decimal(10,6)")] System.Nullable<decimal> lONGITUD_DESTINO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, nOMBRE_VIAJE, lATITUD_DESTINO, lONGITUD_DESTINO);
			return ((ISingleResult<SP_EliminarViajeGuardadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarUsuario")]
		public ISingleResult<SP_InsertarUsuarioResult> SP_InsertarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(50)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(50)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="NVarChar(50)")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_DE_CARGADOR", DbType="NVarChar(50)")] string tIPO_DE_CARGADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(MAX)")] string nUMERO_VERIFICACION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, aPELLIDOS, cORREO_ELECTRONICO, pASSWORD, dIRECCION, tIPO_DE_CARGADOR, nUMERO_VERIFICACION);
			return ((ISingleResult<SP_InsertarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarHistorial")]
		public int SP_InsertarHistorial([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_UBICACION", DbType="NVarChar(100)")] string nOMBRE_UBICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LATITUD", DbType="Decimal(10,6)")] System.Nullable<decimal> lATITUD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LONGITUD", DbType="Decimal(10,6)")] System.Nullable<decimal> lONGITUD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, nOMBRE_UBICACION, lATITUD, lONGITUD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarConsumoEnergia")]
		public int SP_InsertarConsumoEnergia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_REFERENCIA", DbType="NVarChar(100)")] string nOMBRE_REFERENCIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONSUMO_KWH", DbType="Decimal(18,4)")] System.Nullable<decimal> cONSUMO_KWH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, nOMBRE_REFERENCIA, cONSUMO_KWH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarBitacora")]
		public int SP_InsertarBitacora([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASE", DbType="NVarChar(100)")] string cLASE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="METODO", DbType="NVarChar(100)")] string mETODO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="SmallInt")] System.Nullable<short> tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(MAX)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REQUEST", DbType="NVarChar(MAX)")] string rEQUEST, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESPONSE", DbType="NVarChar(MAX)")] string rESPONSE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cLASE, mETODO, tIPO, eRROR_ID, dESCRIPCION, rEQUEST, rESPONSE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarUsuario")]
		public ISingleResult<SP_EliminarUsuarioResult> SP_EliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_EliminarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarHistorial")]
		public ISingleResult<SP_EliminarHistorialResult> SP_EliminarHistorial([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_HISTORIAL", DbType="BigInt")] System.Nullable<long> iD_HISTORIAL)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, iD_HISTORIAL);
			return ((ISingleResult<SP_EliminarHistorialResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarUsuario")]
		public ISingleResult<SP_ActualizarUsuarioResult> SP_ActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(50)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="NVarChar(50)")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_DE_CARGADOR", DbType="NVarChar(50)")] string tIPO_DE_CARGADOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, nOMBRE, aPELLIDOS, dIRECCION, tIPO_DE_CARGADOR);
			return ((ISingleResult<SP_ActualizarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActivarUsuario")]
		public ISingleResult<SP_ActivarUsuarioResult> SP_ActivarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(50)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(MAX)")] string nUMERO_VERIFICACION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO, nUMERO_VERIFICACION);
			return ((ISingleResult<SP_ActivarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarVehiculo")]
		public ISingleResult<SP_ActualizarVehiculoResult> SP_ActualizarVehiculo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MARCA", DbType="NVarChar(50)")] string mARCA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MODELO", DbType="NVarChar(50)")] string mODELO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ANO", DbType="Int")] System.Nullable<int> aNO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO, mARCA, mODELO, aNO);
			return ((ISingleResult<SP_ActualizarVehiculoResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarVehiculo")]
		public ISingleResult<SP_EliminarVehiculoResult> SP_EliminarVehiculo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GUID_USUARIO", DbType="UniqueIdentifier")] System.Nullable<System.Guid> gUID_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gUID_USUARIO);
			return ((ISingleResult<SP_EliminarVehiculoResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_ObtenerViajesGuardadosResult
	{
		
		private string _NOMBRE_VIAJE;
		
		private decimal _LATITUD_DESTINO;
		
		private decimal _LONGITUD_DESTINO;
		
		public SP_ObtenerViajesGuardadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_VIAJE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE_VIAJE
		{
			get
			{
				return this._NOMBRE_VIAJE;
			}
			set
			{
				if ((this._NOMBRE_VIAJE != value))
				{
					this._NOMBRE_VIAJE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD_DESTINO", DbType="Decimal(10,6) NOT NULL")]
		public decimal LATITUD_DESTINO
		{
			get
			{
				return this._LATITUD_DESTINO;
			}
			set
			{
				if ((this._LATITUD_DESTINO != value))
				{
					this._LATITUD_DESTINO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD_DESTINO", DbType="Decimal(10,6) NOT NULL")]
		public decimal LONGITUD_DESTINO
		{
			get
			{
				return this._LONGITUD_DESTINO;
			}
			set
			{
				if ((this._LONGITUD_DESTINO != value))
				{
					this._LONGITUD_DESTINO = value;
				}
			}
		}
	}
	
	public partial class SP_ObtenerVehiculoResult
	{
		
		private string _MARCA;
		
		private string _MODELO;
		
		private int _ANO;
		
		public SP_ObtenerVehiculoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARCA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MARCA
		{
			get
			{
				return this._MARCA;
			}
			set
			{
				if ((this._MARCA != value))
				{
					this._MARCA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODELO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MODELO
		{
			get
			{
				return this._MODELO;
			}
			set
			{
				if ((this._MODELO != value))
				{
					this._MODELO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANO", DbType="Int NOT NULL")]
		public int ANO
		{
			get
			{
				return this._ANO;
			}
			set
			{
				if ((this._ANO != value))
				{
					this._ANO = value;
				}
			}
		}
	}
	
	public partial class SP_ObtenerUsuarioPorGuidResult
	{
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private string _CORREO_ELECTRONICO;
		
		private string _DIRECCION;
		
		private string _PASSWORD;
		
		private string _TIPO_DE_CARGADOR;
		
		private System.Nullable<int> _ESTADO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_ObtenerUsuarioPorGuidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_DE_CARGADOR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TIPO_DE_CARGADOR
		{
			get
			{
				return this._TIPO_DE_CARGADOR;
			}
			set
			{
				if ((this._TIPO_DE_CARGADOR != value))
				{
					this._TIPO_DE_CARGADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
		public System.Nullable<int> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_ObtenerUsuarioPorCorreoResult
	{
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private string _CORREO_ELECTRONICO;
		
		private string _DIRECCION;
		
		private string _TIPO_DE_CARGADOR;
		
		private System.Nullable<int> _ESTADO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_ObtenerUsuarioPorCorreoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_DE_CARGADOR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TIPO_DE_CARGADOR
		{
			get
			{
				return this._TIPO_DE_CARGADOR;
			}
			set
			{
				if ((this._TIPO_DE_CARGADOR != value))
				{
					this._TIPO_DE_CARGADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
		public System.Nullable<int> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_ObtenerHistorialConsumoResult
	{
		
		private string _NombreReferencia;
		
		private decimal _ConsumoKwh;
		
		private decimal _Monto;
		
		private System.DateTime _FechaConsumo;
		
		public SP_ObtenerHistorialConsumoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreReferencia", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreReferencia
		{
			get
			{
				return this._NombreReferencia;
			}
			set
			{
				if ((this._NombreReferencia != value))
				{
					this._NombreReferencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumoKwh", DbType="Decimal(18,4) NOT NULL")]
		public decimal ConsumoKwh
		{
			get
			{
				return this._ConsumoKwh;
			}
			set
			{
				if ((this._ConsumoKwh != value))
				{
					this._ConsumoKwh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(18,2) NOT NULL")]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaConsumo", DbType="DateTime NOT NULL")]
		public System.DateTime FechaConsumo
		{
			get
			{
				return this._FechaConsumo;
			}
			set
			{
				if ((this._FechaConsumo != value))
				{
					this._FechaConsumo = value;
				}
			}
		}
	}
	
	public partial class SP_ObtenerHistorialResult
	{
		
		private long _ID_HISTORIAL;
		
		private string _NOMBRE_UBICACION;
		
		private decimal _LATITUD;
		
		private decimal _LONGITUD;
		
		public SP_ObtenerHistorialResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HISTORIAL", DbType="BigInt NOT NULL")]
		public long ID_HISTORIAL
		{
			get
			{
				return this._ID_HISTORIAL;
			}
			set
			{
				if ((this._ID_HISTORIAL != value))
				{
					this._ID_HISTORIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_UBICACION", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE_UBICACION
		{
			get
			{
				return this._NOMBRE_UBICACION;
			}
			set
			{
				if ((this._NOMBRE_UBICACION != value))
				{
					this._NOMBRE_UBICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD", DbType="Decimal(10,6) NOT NULL")]
		public decimal LATITUD
		{
			get
			{
				return this._LATITUD;
			}
			set
			{
				if ((this._LATITUD != value))
				{
					this._LATITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD", DbType="Decimal(10,6) NOT NULL")]
		public decimal LONGITUD
		{
			get
			{
				return this._LONGITUD;
			}
			set
			{
				if ((this._LONGITUD != value))
				{
					this._LONGITUD = value;
				}
			}
		}
	}
	
	public partial class SP_LoginUsuarioResult
	{
		
		private System.Guid _GUID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private string _CORREO_ELECTRONICO;
		
		private string _PASSWORD;
		
		private string _DIRECCION;
		
		private string _TIPO_DE_CARGADOR;
		
		private System.Nullable<int> _ESTADO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		public SP_LoginUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_DE_CARGADOR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TIPO_DE_CARGADOR
		{
			get
			{
				return this._TIPO_DE_CARGADOR;
			}
			set
			{
				if ((this._TIPO_DE_CARGADOR != value))
				{
					this._TIPO_DE_CARGADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
		public System.Nullable<int> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_InsertarVehiculoResult
	{
		
		private int _Resultado;
		
		private string _Mensaje;
		
		public SP_InsertarVehiculoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int NOT NULL")]
		public int Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this._Resultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_InsertarViajeGuardadoResult
	{
		
		private int _Resultado;
		
		private string _Mensaje;
		
		public SP_InsertarViajeGuardadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int NOT NULL")]
		public int Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this._Resultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(28) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_EliminarViajeGuardadoResult
	{
		
		private int _Resultado;
		
		private string _Mensaje;
		
		public SP_EliminarViajeGuardadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int NOT NULL")]
		public int Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this._Resultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_InsertarUsuarioResult
	{
		
		private int _Resultado;
		
		private string _Mensaje;
		
		private System.Nullable<System.Guid> _GUID_USUARIO;
		
		public SP_InsertarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int NOT NULL")]
		public int Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this._Resultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(28) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID_USUARIO", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GUID_USUARIO
		{
			get
			{
				return this._GUID_USUARIO;
			}
			set
			{
				if ((this._GUID_USUARIO != value))
				{
					this._GUID_USUARIO = value;
				}
			}
		}
	}
	
	public partial class SP_EliminarUsuarioResult
	{
		
		private int _Resultado;
		
		private string _Mensaje;
		
		public SP_EliminarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int NOT NULL")]
		public int Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this._Resultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_EliminarHistorialResult
	{
		
		private int _Resultado;
		
		private string _Mensaje;
		
		public SP_EliminarHistorialResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int NOT NULL")]
		public int Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this._Resultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_ActualizarUsuarioResult
	{
		
		private int _Resultado;
		
		private string _Mensaje;
		
		public SP_ActualizarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int NOT NULL")]
		public int Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this._Resultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_ActivarUsuarioResult
	{
		
		private int _Resultado;
		
		public SP_ActivarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int NOT NULL")]
		public int Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this._Resultado = value;
				}
			}
		}
	}
	public partial class SP_ActualizarVehiculoResult
	{
		private int _Resultado;

		public SP_ActualizarVehiculoResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int NOT NULL")]
		public int Resultado
		{
			get { return this._Resultado; }
			set { if ((this._Resultado != value)) { this._Resultado = value; } }
		}
	}

	public partial class SP_EliminarVehiculoResult
	{
		private int _Resultado;

		public SP_EliminarVehiculoResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int NOT NULL")]
		public int Resultado
		{
			get { return this._Resultado; }
			set { if ((this._Resultado != value)) { this._Resultado = value; } }
		}
	}
}
#pragma warning restore 1591
